import React, { useEffect, useMemo, useState } from 'react';
import { Radio, RefreshCw, Server, Wifi } from 'lucide-react';
import { getNodes } from '../services/api';

export default function Sensors() {
    const [nodes, setNodes] = useState([]), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
    const load = async () => { setLoading(true); setError(''); try { const data = await getNodes(); setNodes(data); setSelected(current => current || data[0] || null); } catch (e) { console.error(e); setError('Unable to retrieve current sensor status.'); } finally { setLoading(false); } };
    useEffect(() => { load(); }, []);
    const active = useMemo(() => nodes.filter(node => node.status === 'active').length, [nodes]);
    return <div className="workspace-page sensors-workspace"><header className="workspace-header"><div><span className="workspace-kicker"><Radio size={13}/> SENSOR MESH</span><h1>Sensor operations</h1><p>Live availability and endpoint status from the LLMPot node network.</p></div><button className="workspace-action" onClick={load} disabled={loading}><RefreshCw size={14} className={loading ? 'animate-spin' : ''}/> Refresh</button></header>{error ? <section className="workspace-empty"><Server size={28}/><b>Sensor service unavailable</b><p>{error}</p><button className="workspace-action" onClick={load}>Retry</button></section> : <div className="sensor-workspace-grid"><section className="workspace-panel sensor-list-panel"><div className="workspace-panel-title"><span>ALL SENSORS</span><b>{active} online</b></div>{loading ? <p className="workspace-loading">Retrieving node telemetry…</p> : nodes.length ? nodes.map(node => <button key={node.id} onClick={() => setSelected(node)} className={`sensor-workspace-row ${selected?.id === node.id ? 'selected' : ''}`}><i className={node.status === 'active' ? 'active' : ''}/><span><b>{node.region || 'Unassigned region'}</b><small>{node.ip || 'Address unavailable'}</small></span><em>{node.status || 'unknown'}</em></button>) : <div className="workspace-empty compact"><Wifi size={24}/><b>No sensors observed</b><p>Nodes will appear when they connect to LLMPot.</p></div>}</section><section className="workspace-panel sensor-detail-panel"><div className="workspace-panel-title"><span>SELECTED SENSOR</span><Wifi size={14}/></div>{selected ? <><div className="sensor-detail-icon"><Server size={48}/><i className={selected.status === 'active' ? 'active' : ''}/></div><h2>{selected.region || 'LLMPot sensor'}</h2><div className="sensor-detail-grid"><span>Address<b>{selected.ip || 'Not available'}</b></span><span>Status<b className={selected.status === 'active' ? 'status-good' : 'status-muted'}>{selected.status || 'Unknown'}</b></span><span>Uptime<b>{selected.uptime_seconds ? `${Math.floor(selected.uptime_seconds / 3600)}h` : 'Not available'}</b></span><span>Last seen<b>{selected.last_seen ? new Date(selected.last_seen).toLocaleString() : 'Not available'}</b></span></div></> : <div className="workspace-empty compact"><Server size={24}/><b>No sensor selected</b></div>}</section></div>}</div>;
}
